version: '2.4'
volumes:
  postgres-data-volume:
  mongodb_data_container:

services:

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: LuiCsf5LUikmnI7TGR
      POSTGRES_DB: ai_novel_generator
      PGUSER: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      service.name: "postgres"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

  mongodb_container:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: F4NB1oPmM60eKHH
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
